# travis
sudo: false
language: python
cache: pip

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=flake8
      after_success:
        - echo "done"

    - python: 3.6
      env: TOXENV=env_var_coverage

    - python: 3.6
      #taken from https://quick-sphinx-tutorial.readthedocs.io/en/latest/advanced.html
      branches:
        only:
          - master

      env: test doc creation
      sudo: false
      install:
        - python -m pip install -U -r requirements_dev.txt
        - python setup.py install
      script:
        - cd docs; make html linkcheck
      # Flags used here, not in `make html`:
      #  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
      #  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.
      after_success:
        - echo "done"

    - language: generic
      python: 2.7
      env: osx-py27
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py27 python=2.7 -y
      install:
        - source activate py27
        - conda config --add channels conda-forge
        - conda install -y --name py27 tox coveralls
        - pip freeze
      script: tox -e py27

    - language: generic
      python: 3.4
      env: osx-py34
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py34 python=3.4 -y
      install:
        - source activate py34
        - conda config --add channels conda-forge
        - conda install -y --name py34 tox coveralls
        - pip freeze
      script: tox -e py34

    - language: generic
      python: 3.5
      env: osx-py35
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py35 python=3.5 -y
      install:
        - source activate py35
        - conda config --add channels conda-forge
        - conda install -y --name py35 tox coveralls
        - pip freeze
      script: tox -e py35

    - language: generic
      python: 3.6
      env: osx-py36
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py36 python=3.6 -y
      install:
        - source activate py36
        - conda config --add channels conda-forge
        - conda install -y --name py36 tox coveralls
        - pip freeze
      script: tox -e py36

    - language: generic
      python: 3.7
      env: osx-py37
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py37 python=3.7 -y
      install:
        - source activate py37
        - conda config --add channels conda-forge
        - conda install -y --name py37 tox coveralls
        - pip freeze
      script: tox -e py37

    - python: 3.6
      env: win_coverage
      install:
        - pip install git+https://github.com/Robpol86/appveyor-artifacts.git coveralls
      script:
        - appveyor-artifacts -m download
      after_success:
        - coveralls
        - coverage erase

install:
  - python -m pip install -U pip>=8.1.2
  - pip install tox-travis coveralls

script: tox

after_success:
    - coveralls
    - coverage erase
